<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GUDU-PC" ignored="0" name="EmployeesRestAPITest" tests="34" failures="13" timestamp="27 May 2021 04:18:37 GMT" time="28.601" errors="0">
  <testcase name="@BeforeClass deleteEmployee" time="3.356" classname="com.employeeapi.testCases.TC005_Delete_Employee_Record">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.employeeapi.testCases.TC005_Delete_Employee_Record.deleteEmployee(TC005_Delete_Employee_Record.java:49)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 33 more
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass deleteEmployee -->
  <testcase name="@AfterClass tearDown" time="0.0" classname="com.employeeapi.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="checkContentLenght" time="0.002" classname="com.employeeapi.testCases.TC001_Get_All_Employees">
    <failure type="java.lang.NumberFormatException" message="null">
      <![CDATA[java.lang.NumberFormatException: null
at java.lang.Integer.parseInt(Integer.java:542)
at java.lang.Integer.parseInt(Integer.java:615)
at com.employeeapi.testCases.TC001_Get_All_Employees.checkContentLenght(TC001_Get_All_Employees.java:137)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- checkContentLenght -->
  <testcase name="checkContentType" time="0.005" classname="com.employeeapi.testCases.TC001_Get_All_Employees">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapi.testCases.TC001_Get_All_Employees.checkContentType(TC001_Get_All_Employees.java:103)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkCookies" time="0.0" classname="com.employeeapi.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkResponseTime" time="0.001" classname="com.employeeapi.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkResposeBody" time="0.028" classname="com.employeeapi.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employeeapi.testCases.TC001_Get_All_Employees">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testCases.TC001_Get_All_Employees.checkStatusCode(TC001_Get_All_Employees.java:63)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkcontentEncoding" time="0.001" classname="com.employeeapi.testCases.TC001_Get_All_Employees">
    <failure type="java.lang.AssertionError" message="expected [gzip] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [gzip] but found [null]
at com.employeeapi.testCases.TC001_Get_All_Employees.checkcontentEncoding(TC001_Get_All_Employees.java:124)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkcontentEncoding -->
  <testcase name="checkserverType" time="0.002" classname="com.employeeapi.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkstatusLine" time="0.001" classname="com.employeeapi.testCases.TC001_Get_All_Employees">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testCases.TC001_Get_All_Employees.checkstatusLine(TC001_Get_All_Employees.java:90)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase name="checkContentLenght" time="0.001" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record">
    <failure type="java.lang.NumberFormatException" message="null">
      <![CDATA[java.lang.NumberFormatException: null
at java.lang.Integer.parseInt(Integer.java:542)
at java.lang.Integer.parseInt(Integer.java:615)
at com.employeeapi.testCases.TC002_Get_Single_Employee_Record.checkContentLenght(TC002_Get_Single_Employee_Record.java:93)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- checkContentLenght -->
  <testcase name="checkContentType" time="0.001" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkResponseTime" time="0.0" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkResposeBody" time="0.001" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkserverType" time="0.0" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkstatusLine" time="0.0" classname="com.employeeapi.testCases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkContentType" time="0.0" classname="com.employeeapi.testCases.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [[text/html; charset=UTF-8] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [[text/html; charset=UTF-8] but found [text/html; charset=UTF-8]
at com.employeeapi.testCases.TC003_Post_Employee_Record.checkContentType(TC003_Post_Employee_Record.java:95)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResposeBody" time="0.001" classname="com.employeeapi.testCases.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testCases.TC003_Post_Employee_Record.checkResposeBody(TC003_Post_Employee_Record.java:72)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkResposeBody -->
  <testcase name="checkStatusCode" time="0.0" classname="com.employeeapi.testCases.TC003_Post_Employee_Record"/>
  <testcase name="checkcontentEncoding" time="0.001" classname="com.employeeapi.testCases.TC003_Post_Employee_Record"/>
  <testcase name="checkserverType" time="0.0" classname="com.employeeapi.testCases.TC003_Post_Employee_Record"/>
  <testcase name="checkstatusLine" time="0.001" classname="com.employeeapi.testCases.TC003_Post_Employee_Record"/>
  <testcase name="checkContentType" time="0.0" classname="com.employeeapi.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapi.testCases.TC004_Put_Employee_Record.checkContentType(TC004_Put_Employee_Record.java:95)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResposeBody" time="0.001" classname="com.employeeapi.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testCases.TC004_Put_Employee_Record.checkResposeBody(TC004_Put_Employee_Record.java:71)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkResposeBody -->
  <testcase name="checkStatusCode" time="0.0" classname="com.employeeapi.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testCases.TC004_Put_Employee_Record.checkStatusCode(TC004_Put_Employee_Record.java:80)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkcontentEncoding" time="0.001" classname="com.employeeapi.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [gzip] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [gzip] but found [null]
at com.employeeapi.testCases.TC004_Put_Employee_Record.checkcontentEncoding(TC004_Put_Employee_Record.java:109)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkcontentEncoding -->
  <testcase name="checkserverType" time="0.001" classname="com.employeeapi.testCases.TC004_Put_Employee_Record"/>
  <testcase name="checkstatusLine" time="0.0" classname="com.employeeapi.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testCases.TC004_Put_Employee_Record.checkstatusLine(TC004_Put_Employee_Record.java:87)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase name="checkContentType" time="0.0" classname="com.employeeapi.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResposeBody" time="0.0" classname="com.employeeapi.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkResposeBody -->
  <testcase name="checkStatusCode" time="0.0" classname="com.employeeapi.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkcontentEncoding" time="0.0" classname="com.employeeapi.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkcontentEncoding -->
  <testcase name="checkserverType" time="0.0" classname="com.employeeapi.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkserverType -->
  <testcase name="checkstatusLine" time="0.0" classname="com.employeeapi.testCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkstatusLine -->
</testsuite> <!-- EmployeesRestAPITest -->
